### ISSUE TITLE
Ticks get calculated wayy too many times

### ISSUE THREAD

**Issue by Quacken8** [chartium/libchartium#75]
May be a symptom of deeper reactivity issue..?

![image](https://github.com/chartium/libchartium/assets/78506690/409dd2cb-c149-467f-ad64-315e7146f4b5)

**Comment by RisaI** [comment]
At the moment there are 6 invocations when creating a chart. 3 short-circuit, the remaining three are:

1. an initial invocation, when the minimal set of dependencies is satisfied
2. a recalculation when `measureTextSize` is provided (only possible after the `AxisTicks` element mounts)
3. canvas resize due to the other chart components mounting

I don't believe there's currently a straightforward way to reduce it even more.
